version: '3'

services:
  mongo-db:
     image: mongo
     container_name: mongo-db
     hostname: mongo-db
     networks:
        default:
           aliases:
              - mongo-db
     ports:                  
        - "27017:27017"
  a-simple-server:
     build: a-simple-server
     links: 
       - mongo-db
     ports:
       - 3000:3000
       